defaults:
  - _self_
  - _datasets
  - _model

data:

  # Available tasks: hallucination
  task: hallucination

  # Available tasks: pdb, scope. Decide which dataset to use.
  dataset: pdb
  rectify: False # Set to True for rectify training


  loader:
    num_workers: 4
    prefetch_factor: 10

  sampler:
    max_batch_size: 128
    max_num_res_squared: 1000000

interpolant:
  min_t: 1e-2

  twisting:
    use: False

  rots:
    corrupt: True
    sample_schedule: exp
    exp_rate: 10

  trans:
    corrupt: True
    batch_ot: True
    sample_schedule: linear
    sample_temp: 1.0
    vpsde_bmin: 0.1
    vpsde_bmax: 20.0
    potential: null
    potential_t_scaling: False
    rog:
      weight: 10.0
      cutoff: 5.0

  sampling:
    num_timesteps: 100
    do_sde: False

  self_condition: ${model.edge_features.self_condition}

experiment:
  is_training: False # Set to true for training, false for inference
  debug: False
  seed: 123
  num_devices: 4
  warm_start: null
  warm_start_cfg_override: True
  resume_cfg_path: null
  resume_ckpt_path: null
  resume: False
  training:
    mask_plddt: True
    bb_atom_scale: 0.1
    trans_scale: 0.1
    translation_loss_weight: 2.0
    t_normalize_clip: 0.9
    rotation_loss_weights: 1.0
    aux_loss_weight: 1.0
    aux_loss_use_bb_loss: True
    aux_loss_use_pair_loss: True
    aux_loss_t_pass: 0.50 # 0.25 for scope, 0.5 for pdb
  wandb:
    name: reqflow_train_pdb_base
    project: reqflow
  optimizer:
    lr: 0.0001
  trainer:
    overfit_batches: 0
    min_epochs: 1 # prevents early stopping
    max_epochs: 1000
    accelerator: gpu
    log_every_n_steps: 1
    deterministic: False
    strategy: ddp
    check_val_every_n_epoch: 1
    accumulate_grad_batches: 2
  checkpointer: # where to save checkpoints
    dirpath: ./ckpts/${experiment.wandb.project}/${experiment.wandb.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    save_last: True
    save_top_k: -1

  # Keep this null. Will be populated at runtime.
  inference_dir: null
